#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
        /app \
        /archive \
        /config \
        /opt

if [[ ! -h /opt/${COMPANY_NAME}/mediaserver/var ]]
then
  if [[ -d /config/var ]]
  then
    rm -rf /opt/${COMPANY_NAME}/mediaserver/var
  elif [[ ! -d /config/var ]]
  then
    mv /opt/${COMPANY_NAME}/mediaserver/var /config/var
  fi
  ln -s /config/var /opt/${COMPANY_NAME}/mediaserver/var
else
  if [[ ! -d /config/var ]]
  then
    mkdir /config/var
    chown -R abc:abc /config/var
  fi
fi

if [[ ! -h /opt/${COMPANY_NAME}/mediaserver/etc ]]
then
  if [[ -d /config/etc ]]
  then
    rm -rf /opt/${COMPANY_NAME}/mediaserver/etc
  elif [[ ! -d /config/etc ]]
  then
    mv /opt/${COMPANY_NAME}/mediaserver/etc /config/etc
  fi
  ln -s /config/etc /opt/${COMPANY_NAME}/mediaserver/etc
else
  if [[ ! -d /config/opt ]]
  then
    mkdir /config/opt
    chown -R abc:abc /config/opt
  fi
fi
