#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
	/app \
	/archive \
	/config \
        /opt

if [[ ! -d /config/var ]]
then
  mv /opt/digitalwatchdog/mediaserver/var /config/var
  rm -rf /opt/digitalwatchdog/mediaserver/var
  ln -s /config/var /opt/digitalwatchdog/mediaserver/var
else
  rm -rf /opt/digitalwatchdog/mediaserver/var
  ln -s /config/var /opt/digitalwatchdog/mediaserver/var
fi

if [[ ! -d /config/etc ]]
then
  mv /opt/digitalwatchdog/mediaserver/etc /config/etc
  rm -rf /opt/digitalwatchdog/mediaserver/etc
  ln -s /config/etc /opt/digitalwatchdog/mediaserver/etc
else
  rm -rf /opt/digitalwatchdog/mediaserver/etc
  ln -s /config/etc /opt/digitalwatchdog/mediaserver/etc
fi
