#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
        /app \
        /archive \
        /config \
        /opt

if [[ ! -h /opt/${COMPANY_NAME}/mediaserver/var ]]
then
  if [[ -d /config/var ]]
  then
    rm -rf /opt/${COMPANY_NAME}/mediaserver/var
  elif [[ ! -d /config/var ]]
  then
    mv /opt/${COMPANY_NAME}/mediaserver/var /config/var
  fi
  ln -s /config/var /opt/${COMPANY_NAME}/mediaserver/var
else
  if [[ ! -d /config/var ]]
  then
    mkdir /config/var
    chown -R abc:abc /config/var
  fi
fi

if [[ ! -h /opt/${COMPANY_NAME}/mediaserver/etc ]]
then
  if [[ -d /config/etc ]]
  then
    rm -rf /opt/${COMPANY_NAME}/mediaserver/etc
  elif [[ ! -d /config/etc ]]
  then
    mv /opt/${COMPANY_NAME}/mediaserver/etc /config/etc
  fi
  ln -s /config/etc /opt/${COMPANY_NAME}/mediaserver/etc
else
  if [[ ! -d /config/etc ]]
  then
    mkdir /config/etc
    chown -R abc:abc /config/etc
  fi
fi

if [[ -n ${LISTEN_PORT} ]]
then
  if [[ -f /config/etc/mediaserver.conf ]]
  then
    echo "mediaserver.conf exists"
    if [[ $(grep -Ec '^port=' /config/etc/mediaserver.conf) -gt 0 ]]
    then
      echo "port value exists, updating"
      sed -i "s/^port=.*/port=${LISTEN_PORT}/" /config/etc/mediaserver.conf
    else
      echo "port value doesn't exist, adding"
      echo "port=${LISTEN_PORT}" >> /config/etc/mediaserver.conf
    fi
  else
    echo "mediaserver.conf doesn't exist, creating"
    #echo "[General]" >> /config/etc/mediaserver.conf
    echo "port=${LISTEN_PORT}" >> /config/etc/mediaserver.conf
  fi
fi
